fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=GNU]
      - id: clang-tidy
        args: [--fix-errors]
      - id: oclint
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
