repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["-i", "--style=GNU"]
      - id: clang-tidy
        args: ["--fix-errors"]
      - id: oclint
      - id: cppcheck
      - id: cpplint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-symlinks
    - id: check-merge-conflict
    - id: check-json
    - id: check-added-large-files
      args: [--maxkb=51200]
